'use client'

import Link from 'next/link'
import { useState } from 'react'

const FAQS = [
  {
    category: 'General',
    questions: [
      { q: 'What is Guideway?', a: 'Guideway is a personalized high school success platform. You answer 7 questions about your grade, GPA, goals, and struggles — and Guideway builds you a custom plan covering your study schedule, extracurriculars, college roadmap, and more. It updates every week based on how things are going.' },
      { q: 'Who is Guideway for?', a: 'Any high school student in grades 9-12. Whether you are aiming for a top university, a trade school, or still figuring it out — Guideway builds a plan around your actual goals, not a generic template.' },
      { q: 'Who built Guideway?', a: 'Guideway was built by Varun, a sophomore in Virginia, after seeing how many students had no real system for navigating high school. It was validated by 35+ students before launch.' },
      { q: 'Is Guideway really personalized?', a: 'Yes. Every plan is generated by AI based on your specific profile — your grade, GPA, struggles, interests, available time, stress level, and goals. No two plans are the same.' },
    ]
  },
  {
    category: 'Pricing',
    questions: [
      { q: 'How much does Guideway cost?', a: 'Guideway has a free tier that gives you a basic AI-generated plan. The Pro tier is $5/month and includes a fully personalized plan, weekly check-ins that update your plan, mental health strategies, opportunity recommendations, and priority AI.' },
      { q: 'Can I cancel anytime?', a: 'Yes — cancel anytime from your account settings. No questions asked, no hidden fees.' },
      { q: 'Is there a student discount?', a: 'Guideway is already priced for students at $5/month. If you genuinely cannot afford it, reach out — we will work something out.' },
      { q: 'Does my school or district get a different price?', a: 'Yes. School and district licensing starts at $2,500/year for a single school and $15,000/year for county-wide access. Contact us for a custom quote.' },
    ]
  },
  {
    category: 'Features',
    questions: [
      { q: 'What does the weekly check-in do?', a: 'Every week, you answer 6 quick questions about how your week went — what you completed, your stress level, any new goals. Guideway uses this to regenerate your plan so it stays current with your real life.' },
      { q: 'What study tools does Guideway include?', a: 'Guideway includes a homework and assignment tracker, GPA and grade calculator, class schedule timetable, exam countdown, Pomodoro focus timer, and an AI study buddy that knows your profile and helps you study specific subjects.' },
      { q: 'What is the AI study buddy?', a: 'The AI study buddy is a chat assistant that knows your grade, GPA, struggles, and interests. You can ask it to explain concepts, quiz you on topics, help you study for a specific exam, or give you advice tailored to your situation.' },
      { q: 'Does my plan update automatically?', a: 'Your plan updates after every weekly check-in. You can also rebuild your plan anytime from the dashboard if your situation changes significantly.' },
    ]
  },
  {
    category: 'Privacy & Security',
    questions: [
      { q: 'Is my data safe?', a: 'Yes. Guideway uses Supabase for authentication and data storage, with row-level security ensuring only you can access your data. We never sell your data.' },
      { q: 'Do you share my information with anyone?', a: 'No. Your profile data is used only to generate your personalized plan. We do not sell, share, or distribute your personal information.' },
      { q: 'Can I delete my account?', a: 'Yes. Go to Settings and scroll to the bottom — you will find a delete account option. This permanently removes all your data.' },
    ]
  },
]

export default function FAQ() {
  const [open, setOpen] = useState<string | null>(null)

  return (
    <main className="min-h-screen bg-white" style={{ fontFamily: "'Inter', sans-serif" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,700;1,9..144,700&family=Inter:wght@400;500;600&display=swap');
        .brand { font-family: 'Fraunces', serif; }
      `}</style>

      <nav className="sticky top-0 z-50 bg-white/90 backdrop-blur-md border-b border-stone-100">
        <div className="flex items-center justify-between px-8 py-3.5 max-w-7xl mx-auto">
          <Link href="/" className="brand text-xl text-stone-900">Guideway</Link>
          <div className="flex items-center gap-4">
            <Link href="/pricing" className="text-sm text-stone-400 hover:text-stone-700 transition">Pricing</Link>
            <Link href="/contact" className="text-sm text-stone-400 hover:text-stone-700 transition">Contact</Link>
            <Link href="/login" className="text-sm text-stone-400 hover:text-stone-700 transition">Log in</Link>
            <Link href="/signup" className="text-sm bg-stone-900 text-white px-4 py-2 rounded-lg hover:bg-stone-700 transition font-medium">Get started</Link>
          </div>
        </div>
      </nav>

      <section className="max-w-3xl mx-auto px-8 pt-20 pb-12">
        <p className="text-xs font-semibold text-stone-400 uppercase tracking-widest mb-4">FAQ</p>
        <h1 className="brand text-6xl text-stone-900 leading-tight mb-4">Common questions.</h1>
        <p className="text-lg text-stone-400">Everything you need to know about Guideway. Can&apos;t find your answer? <Link href="/contact" className="text-[#4a7c59] hover:underline">Contact us</Link>.</p>
      </section>

      <div className="border-t border-stone-100" />

      <section className="max-w-3xl mx-auto px-8 py-16">
        <div className="flex flex-col gap-12">
          {FAQS.map(({ category, questions }) => (
            <div key={category}>
              <p className="text-xs font-bold text-stone-400 uppercase tracking-widest mb-6">{category}</p>
              <div className="flex flex-col gap-2">
                {questions.map(({ q, a }) => (
                  <div key={q} className="border border-stone-100 rounded-2xl overflow-hidden">
                    <button
                      onClick={() => setOpen(open === q ? null : q)}
                      className="w-full flex items-center justify-between px-6 py-4 text-left hover:bg-stone-50 transition"
                    >
                      <span className="text-sm font-semibold text-stone-800 pr-4">{q}</span>
                      <svg
                        width="16" height="16" viewBox="0 0 16 16" fill="none"
                        className={`flex-shrink-0 transition-transform duration-200 ${open === q ? 'rotate-180' : ''}`}
                      >
                        <path d="M3 6l5 5 5-5" stroke="#94a3b8" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                      </svg>
                    </button>
                    {open === q && (
                      <div className="px-6 pb-5 border-t border-stone-50">
                        <p className="text-sm text-stone-400 leading-relaxed pt-4">{a}</p>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </section>

      <div className="border-t border-stone-100" />

      <section className="max-w-3xl mx-auto px-8 py-20 text-center">
        <h2 className="brand text-4xl text-stone-900 mb-4">Still have questions?</h2>
        <p className="text-stone-400 mb-8">We are happy to help. Reach out and we will get back to you within 2 business days.</p>
        <Link href="/contact" className="inline-block bg-[#4a7c59] text-white px-8 py-4 rounded-xl text-base font-semibold hover:bg-[#3d6849] transition">
          Contact us →
        </Link>
      </section>

      <footer className="border-t border-stone-100 px-8 py-6 flex items-center justify-between max-w-7xl mx-auto">
        <span className="brand text-lg text-stone-900">Guideway</span>
        <p className="text-xs text-stone-300">© 2025 Guideway. Built for students, by a student.</p>
      </footer>
    </main>
  )
}